### PR TITLE
Create it_it

### PR DESCRIPTION
**Pull request by CapoFantasma97**
Translation in Italian.

What's the context of "container.alloy_forgery.rei.button": "Cycle Tier Overrides" ?

### CODE REVIEW

**Comment by Noaaan** [comment]
When using [Roughly Enough Items](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items) you are able to cycle through the different outputs when viewing recipes with overrides. 
An example is smelting raw gold into ingots: a tier 1 forge smelts two ores down into three ingots, while a tier 2 forge instead yields you four ingots.
I will attach a screenshot (or video) in a bit showing this functionality, unless someone else does it first

**Comment by CapoFantasma97** [comment]
> When using [Roughly Enough Items](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items) you are able to cycle through the different outputs when viewing recipes with overrides. An example is smelting raw gold into ingots: a tier 1 forge smelts two ores down into three ingots, while a tier 2 forge instead yields you four ingots. I will attach a screenshot (or video) in a bit showing this functionality, unless someone else does it first

I see it now, testing it in game, thanks for the explaination. But why call it “cycle tier overrides” instead of just “cycle between tiers”? Or am I missing something here?

**Comment by Noaaan** [comment]
There is no specific reason for this. Technically speaking this is what you are doing: cycling between the tier overrides defined in the current recipe. 
If you feel it translates better to "cycle between tiers", feel free to do so

**Comment by CapoFantasma97** [comment]
Good to go! 👍

**Review by Noaaan — APPROVED** [review]

**Pull request merged**
