### PR TITLE
Update dependencies and gradle wrapper, add jitpack.yml

### PR DESCRIPTION
**Pull request by Obydux**

### CODE REVIEW

**Comment by Noaaan** [comment]
Care to describe why/what this PR is for? I am confused considering it came out of nowhere in the middle of our development

**Comment by Obydux** [comment]
These changes were needed in order to get the PolyFactory mod to work with Alloy  Forgery in 1.20.4 + this branch didn't build cause of the owo-lib dependency used a missing version 0.12.0-pre.5.1

**Comment by Dragon-Seeker** [comment]
Such was due to owo's development within Endec needing to be tested thru a local version. The rest of the changes for commented-out dependency, updating various aspects of gradle, and bumping the mod version are not strictly needed.

It will be needed on release to bump the dependency with the FMJ but it is not needed to put AF on jitpack due to the fact you can use modrinth as maven and there is a open PR for adding proper dependency within the future on release.

**Comment by Dragon-Seeker** [comment]
I'm closing this PR, with the changes being already planned for release. Jitpack support is not planned for the future and suggest using modrinth as a maven target within the future.

**Pull request closed without merging**
